sonar.projectKey=taller-sast
sonar.projectName=Taller SAST
sonar.projectVersion=1.0.0

sonar.sources=apps
sonar.sourceEncoding=UTF-8
sonar.language=ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.next/**,**/coverage/**,**/*.spec.ts,**/*.test.ts,**/*.stories.tsx
sonar.typescript.node=false