sonar.projectKey=taller-sast
sonar.projectName=Taller SAST
sonar.projectVersion=1.0.0

sonar.sources=apps
sonar.sourceEncoding=UTF-8
sonar.language=ts

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.next/**,**/coverage/**,**/*.stories.tsx

# Excluir tests de cobertura (para no contaminar la métrica)
sonar.coverage.exclusions=**/*.spec.ts,**/*.test.ts,**/__tests__/**

# Indicar dónde están los tests (para reportes)
sonar.tests=apps,services,packages
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts

sonar.typescript.node=false